### ISSUE TITLE
Skills task list.

### ISSUE THREAD

**Issue by friendbear** [friendbear/skills-release-based-workflow#1]
## Step

- [x] Create a beta release
- [x] Add a feature to a release-
- [x] Open a release pull request
- [x] Add release notes and merge
- [x] Finalize a release
- [x] Commit a hotfix
- [x] Create a hotfix release
